name: Test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Apache Arrow
      run: |
        sudo apt update
        sudo apt install -y -V ca-certificates lsb-release wget
        wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt install -y -V ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt update
        sudo apt install -y -V libarrow-glib-dev # For GLib (C)
        sudo apt install -y -V libparquet-glib-dev # For Apache Parquet GLib (C)
    - name: Set up Ruby + Bundle
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

  test:
    runs-on: ubuntu-latest

    needs:
    - build

    steps:
    - name: Run the default task
      run: bundle exec rake
