name: Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Apache Arrow
      run: |
        sudo apt update
        sudo apt install -y -V ca-certificates lsb-release wget
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt update
        sudo apt install -y -V libarrow-glib-dev # For GLib (C)
        sudo apt install -y -V libparquet-glib-dev # For Apache Parquet GLib (C)
    - name: Set up Ruby (mise)
      uses: jdx/mise-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bundle install
      run: bundle install
    - name: Run the default task
      run: bundle exec rake

  bundle-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Apache Arrow
      run: |
        sudo apt update
        sudo apt install -y -V ca-certificates lsb-release wget
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt update
        sudo apt install -y -V libarrow-glib-dev # For GLib (C)
        sudo apt install -y -V libparquet-glib-dev # For Apache Parquet GLib (C)
    - name: Set up Ruby (mise)
      uses: jdx/mise-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bundle install
      run: bundle install
    - name: Audit the bundle
      run: bundle exec bundle-audit check --update
